name: epub_kitty
description: 'epub_kitty is an epub ebook reader that encapsulates the folioreader framework.'
version: 0.1.9
homepage: https://github.com/451518849/epub_kitty

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.xiaofwang.epub_kitty
    pluginClass: EpubKittyPlugin